import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import Provider from '@/providers/Provider';
import './globals.css';
import { Suspense } from 'react';

const outfit = Outfit({
  variable: '--font-outfit-sans',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Super',
  description: 'Generated by create next app'
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} dark:bg-gray-900`}>
        <Suspense fallback={<div>Loading...</div>}>
          <Provider>{children}</Provider>
        </Suspense>
      </body>
    </html>
  );
}
